services:
  fastapi:
    build:
      context: .
    env_file:
      - .env
    entrypoint: sh -c "gunicorn -w 4 main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/db_data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro

    depends_on:
      - fastapi
    ports:
      - "80:80"


volumes:
  db_data: