name: Movies
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        # stop the build if there Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-sorce --statistics
        # exit-zero treats all errors as warnings. The GiyGub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest 
      run: |
        pytest tests/unit
